name: Release
on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'alpha'
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js and semantic-release plugins
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
