name: Release
on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'alpha'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: |
          ls -la
          cd src
          ls -la
          go mod download
          go mod verify
          GOOS=linux && go build -o $PWD/bin/arbotgo
          GOOS=windows && go build -o $PWD/bin/arbotogo.exe
      - name: Setup Node.js and semantic-release plugins
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/release-notes-generator
      - name: Release
        run: npx semantic-release
